_convert_: all

dataloader:
  batch_size: 128
  num_workers: 1
  pin_memory: true
  drop_last: false

dataset:
  seed: ${seed}
  dtype: float32
  cache_capacity: 1024
  seq_len: ${model.seq_len}
  genders: [ "male" ]

  data_dir_name: merged
  filename_pattern: merged

  data_type_probs:
    syn_arb: 0.5
    syn_sup: 0.25
    real: 0.25

  marker_sampler:
    distance_from_skin: 0.01
    min_sample_markers: 44
    max_sample_markers: 88

  dataset_names:
    train: [ "HDM05" ]
    val: [ "HDM05" ]

  noise:
    jitter:
      enabled: true
      max_distance: 0.01
      distance_beta: 5

    ghost:
      enabled: true
      num_tracks: [0, 3]
      num_tracks_sigma: 2.94
      track_len: [1, 5]
      track_len_sigma: 10
      distance: [0.005, 1]
      max_deg_from_normal: 70.0

    occlusion:
      enabled: true
      num_tracks: [0, 5]
      num_tracks_sigma: 2.29
      track_len: [1, 10]
      track_len_sigma: 10

    shuffle:
      enabled: true