defaults:
  - dataset: default
  - model: default
  - solver: default
  - logger: wandb
  - _self_

seed: 42
out_dir: ${hydra:runtime.cwd}/../outputs
use_cuda: true

trainer:
  max_epochs: 100
  log_interval: 100
  val_interval: 1
  train_sample_interval: 1
  val_sample_interval: 1

  amp: true
  grad_clip_norm: 1.0

  optimizer:
    learning_rate: 1e-3
    weight_decay: 0.001

  in_data_keys: ["markers_seq", "markers_seq_mask"]
  gt_data_keys: ["weights", "rep_weights", "rep_offsets", "markers_mask"]
  gt_data_loss:
    weights:
      pred_key: "weights"
      gt_key: "weights"
      mask_key: "markers_mask"
      weight: 1.0
      fn: kl
    rep_weights:
      pred_key: "rep_weights"
      gt_key: "rep_weights"
      mask_key: "markers_mask"
      weight: 1.0
      fn: l2
    rep_offsets:
      pred_key: "rep_offsets"
      gt_key: "rep_offsets"
      mask_key: "markers_mask"
      weight: 100.0
      fn: l1

hydra:
  run:
    dir: ${out_dir}/${now:%Y%m%d_%H%M%S}_${model.name}
  job:
    chdir: true
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
      file:
        class: logging.FileHandler
        level: INFO
        formatter: detailed
        filename: app.log
        mode: a
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] %(message)s"
      detailed:
        format: "[%(asctime)s][%(levelname)s][%(name)s] %(message)s"
    root:
      level: INFO
      handlers: [console, file]
