_target_: damo.model.damo.Damo

name: Damo
seq_len: 7
n_joints: 22
n_rep_joints: 3

default_act: gelu_tanh
default_norm: ln

marker_embedding:
  d_hidden: 128

marker_attention:
  d_model: 125
  n_heads: 5
  n_layers: 4
  seq_len: ${..seq_len}
  use_time_pe: true
  use_dist_bias: false
  attn_dropout: 0.1

  ffn:
    d_model: ${..d_model}
    d_hidden: 128
    act: ${model.default_act}
    dropout: 0.1

  dist_bias:
    n_heads: ${..n_heads}
    init_tau: 0.7

post_attention:
  d_hidden: 256

rep_joint_predictor:
  d_hidden: 256

rep_weight_predictor:
  d_hidden: 256

rep_offset_predictor:
  d_hidden: 256